spring.application.name=topnismatch
server.port=8080

# ?? BASE DE DATOS POSTGRESQL ??????????????????
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.sauuevdgujejyyxbofvg
spring.datasource.password=TopnisMatch2026#
spring.datasource.driver-class-name=org.postgresql.Driver

# ?? JPA / HIBERNATE ???????????????????????????
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ?? LOGS ??????????????????????????????????????
logging.level.org.springframework.security=DEBUG
logging.level.com.topnismatch=DEBUG

# ?? JWT ???????????????????????????????????????
jwt.secret=TopnisMatchSecretKey2026JWTSecurityKeyMustBe256BitsLongForHS256Algorithm
jwt.expiration=86400000